export const StakingPoolsObject = [
  {
    id: 1,
    title: 'BUSD',
    apr: '7%',
    amount: '$300M',
    swap: 'PUFF/BUSD',
    button: 'Deposit BUSD',
  },
  {
    id: 2,
    title: 'BNB',
    apr: '7%',
    amount: '$300M',
    swap: 'PUFF/BNB',
    button: 'Deposit BNB',
  },
  {
    id: 3,
    title: 'PUFF',
    apr: '7%',
    amount: '$300M',
    swap: 'PUFF',
    button: 'STAKE AND VOTE',
  },
  {
    id: 4,
    title: 'PUFF PANCAKE LP',
    apr: '7%',
    amount: '$300M',
    swap: 'PUFF/BUSD',
    button: 'Deposit Pancake LP',
  },
  {
    id: 5,
    title: 'PUFF BABY LP',
    apr: '7%',
    amount: '$300M',
    swap: 'PUFF/BUSD',
    button: 'Deposit Baby LP',
  },
]
