export const StakingPoolsObject = [
  {
    id: 1,
    title: 'MIM',
    apr: '7%',
    amount: '$300M',
    swap: 'BAKD/MIM',
    button: 'Deposit MIM',
  },
  {
    id: 2,
    title: 'FTM',
    apr: '7%',
    amount: '$300M',
    swap: 'BAKD/FTM',
    button: 'Deposit FTM',
  },
  {
    id: 3,
    title: 'BAKD',
    apr: '7%',
    amount: '$300M',
    swap: 'BAKD',
    button: 'STAKE AND VOTE',
  },
  {
    id: 4,
    title: 'BAKD SPOOKY LP',
    apr: '7%',
    amount: '$300M',
    swap: 'BAKD/MIM',
    button: 'Deposit Spooky LP',
  },
  {
    id: 5,
    title: 'BAKD SPIRIT LP',
    apr: '7%',
    amount: '$300M',
    swap: 'BAKD/MIM',
    button: 'Deposit Spirit LP',
  },
]
